controller_list:
  - name: fake_Manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_Gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses.
  - group: Manipulator
    pose: HomePose
  - group: Gripper
    pose: Open